home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    # url(r'^home/', views.index, name='index'),
]

resorts/urls.py
from django.conf.urls import url

from . import views

app_name = 'resorts'
urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^uaac/', views.uaac, name = 'uaac'),
    url(r'^alta/', views.alta, name = 'alta'),
    url(r'^snowbird/', views.snowbird, name = 'snowbird'),
    url(r'^brighton/', views.brighton, name = 'brighton'),
    url(r'^solitude/', views.solitude, name = 'solitude'),
]

snow_site/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^weather/', include('weather.urls')),
    url(r'^resorts/', include('resorts.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('home.urls')),
]

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render


def index(request):
    context = {'response' : "Welcome to Wasatch Snow Reports, your one-stop shop for all Cottonwood snow and weather needs. Here you can find snow and weather information for all the Cottonwood Canyon ski resorts as well as backcountry information from the Utah Avalanche Center (UAC)."}
    return render(request, 'home/index.html', context)

home/templates/home/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="{% static 'images/favicon4.ico' %}">

  <title> {% block title %}Snow Reports{% endblock %}</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'carousel.css' %}" rel="stylesheet">


  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'home/starter-template.css' %}" rel="stylesheet">
  <link href="{% static 'other.css' %}" rel="stylesheet">

  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
  <!-- <script src="{% static 'jquery.js' %}"></script> -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

<body>
  <nav class="navbar navbar-inverse navbar-fixed-top" style="background-color:#243743; color:28b78d;">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="https://github.com/walkersorlie/snow-reports">Wasatch Snow Reports GitHub</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'home:index' %}">Home</a></li>
          <li><a href="{% url 'resorts:uaac' %}">UAC</a></li>
        </ul>
        <div class="dropdown">
          <a href="{% url 'resorts:index' %}"><button class="dropbtn">Resorts<span class="caret"></span></button></a>
          <div class="dropdown-content">
            <a href="{% url 'resorts:alta' %}">Alta</a>
            <a href="{% url 'resorts:snowbird' %}">Snowbird</a>
            <a href="{% url 'resorts:brighton' %}">Brighton</a>
            <a href="{% url 'resorts:solitude' %}">Solitude</a>
          </div>
        </div>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div style="background:#eee;">
    {% block body %}
    {% endblock %}
  </div>

  <!-- Bootstrap core JavaScript
  ================================================== -->
  <!-- Placed at the end of the document so the pages load faster -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script>window.jQuery || document.write('<script src="{static 'jquery.min.js' %"><\/script>')</script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
  <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
  <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

home/templates/home/index.html
{% extends 'home/base.html' %}
{% load static %}

{% block body %}
<!-- Carousel
================================================== -->
<div id="myCarousel" class="carousel slide" data-ride="carousel" style="margin-bottom: 30px;">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
    <li data-target="#myCarousel" data-slide-to="3"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <img class="first-slide" src="{% static 'images/carousel2.jpg' %}" alt="First slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Check out the resorts page</h1>
          <p><a class="btn btn-lg btn-primary" href="{% url 'resorts:index' %}" role="button">View Resorts</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="second-slide" src="{% static 'images/carousel-tour2.jpg' %}" alt="Second slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Utah Avalanche Center</h1>
          <p><a class="btn btn-lg btn-primary" href="{% url 'resorts:uaac' %}" role="button">View Report</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="third-slide" src="{% static 'images/snowbird-carousel2.jpg' %}" alt="Third slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Check out the resorts page</h1>
          <p><a class="btn btn-lg btn-primary" href="{% url 'resorts:index' %}" role="button">View Resorts</a></p>
        </div>
      </div>
    </div>
    <div class="item">
      <img class="fourth-slide" src="{% static 'images/carousel-tour1.jpg' %}" alt="Fourth slide">
      <div class="container">
        <div class="carousel-caption">
          <h1>Utah Avalanche Center</h1>
          <!-- <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p> -->
          <p><a class="btn btn-lg btn-primary" href="{% url 'resorts:uaac' %}" role="button">View Report</a></p>
        </div>
      </div>
    </div>
  </div>
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <!-- <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> -->
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <!-- <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> -->
    <span class="sr-only">Next</span>
  </a>
</div><!-- /.carousel -->
<div class="container">

  <div class="starter-template">
    <div>
      <h3>{{ response }}</h3>
    </div>
  </div>

  <div class="row home-row">
    <div class="col-lg-6">
      <div class="image2" style="height: 481px;">
      <a href="{% url 'resorts:index' %}"><img src="{% static 'images/lcc.jpg' %}" style="width:100%; height: 100%;"></img></a>
    </div>
    <div class="resorts-name" style="width: 555px;">
      <h2>Resorts</h2>
    </div>
    </div>
    <div class="col-lg-6 home-row">
      <h4 style="margin-top: 150px;">The ski resorts of the Cottonwood Canyons&mdash;Alta, Snowbird, Brighton, and Solitude&mdash;receive some of the best snow on earth, and a lot of it! Each resort page has snow information (such as snow in the past twelve hours, base depth, and total snow) and weather (such as current winds and future forecast) available for interested snow riders.</h4>
    </div>
  </div>
  <div class="row home-row">
    <div class="col-lg-6">
      <h4 style="margin-top: 150px;">The Utah Avalanche Center(UAC) is a a 501(c)(3) non-profit organization partnering with the Forest Service. Their mission is to keep people on top of the Greatest Snow on Earth™, which they do by giving winter backcountry travelers the tools they need to stay alive and have fun in avalanche terrain. The UAC covers the entire state of Utah and has offices in Logan, Salt Lake City, and Moab.</h4>
    </div>
    <div class="col-lg-6">
        <!-- <h2 style="text-align: center;">Utah Avalanche Center</h2> -->
        <div class="image2">
          <a href="{% url 'resorts:uaac' %}"><img src="{% static 'images/uac.jpg' %}" style="width: 100%; height: 100%;"></img></a>
        </div>
        <div class="resorts-name" style="width: 555px;">
          <h2>Utah Avalanche Center</h2>
        </div>
    </div>
  </div>

</div><!-- /.container -->
{% endblock %}